build: off

init:
  - git config --global core.autocrlf input

install:
  - cinst adoptopenjdk8
  - mv "C:\Program Files\AdoptOpenJDK" C:\jdk8
  - cinst adoptopenjdk11
  - mv "C:\Program Files\AdoptOpenJDK" C:\jdk11
  - SET JAVA_HOME=C:\jdk8
  - SET PATH=C:\jdk8\bin;%PATH%

  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://piccolo.link/sbt-0.13.18.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - SET PATH=C:\sbt\sbt\bin;%PATH%
  - SET SBT_OPTS=-Xmx4g -Dfile.encoding=UTF8

test_script:
  - sbt "-Dsbt.build.version=1.3.0-M4" universal:packageBin
  - cd citest
  - test.bat
  - test1.bat
  - test2.bat
  - test3/test3.bat
